Quotes Language:		germanguillemets
Base Header Level:	3
latex input:				basis-mmd-scrartcl
MyOptions:					font=droid, rules
latex input:				basis-mmd-style
Title:							Handbuch für Spielverantwortliche
MySubtitle:					OpenTT
Author:							Ekkart Kleinod
MyEmail:						schiri@ekkart.de
MyDate:							Stand: 14. Ausgabe, Juni 2011
latex input:				basis-mmd-begin-doc

<!-- \maketitle -->

<!-- \section*{Vorwort} -->
<h3>Vorwort</h3>

Dies ist eine deutsche Übersetzung des "Handbook for Match Officials" der International Table Tennis Federation (ITTF).[^fussnote:ittf]
Die Übersetzung wird unabhängig von der ITTF angefertigt, die ITTF hat also mit der Korrektheit der Übersetzung nichts zu tun.

Wer einen Fehler oder eine bessere Übersetzung findet: einfach eine E-Mail schreiben oder per Git am Dokument mitschreiben.

Da mir die Übersetzung selbst schon viel Mühe bereitet, werde ich in der ersten Version auf durchgängiges Gendern verzichten, wer das übernehmen möchte ist herzlich dazu eingeladen.

Mit **todo** sind Stellen gekennzeichnet, deren Übersetzung mir noch nicht gut gefällt.

<!-- \cleardoublepage -->
<!-- \tableofcontents -->
<!-- \cleardoublepage -->


# Einleitung

1. Der Zweck dieses Buchs ist es, Spielverantwortliche bei der Anwendung der Regeln und Regularien **todo** zu begleiten.
	Das Buch sollte in Verbindung mit dem aktuellen ITTF-Handbuch oder den Regeln gelesen werden.
	Dieses Buch beschäftigt sich hauptsächlich mit den Pflichten von Oberschiedsrichtern und deren Assistenten, enthält aber auch Aspekte der Aufgaben von Schiedsrichtern beim Leiten eines Spiels.
	Das "Handbuch für Oberschiedsrichter eines Turniers"[^fussnote:hbtr] beschreibt die weiteren Pflichten eines Oberschiedsrichters eines Turniers.

2. Spieler müssen sich darauf verlassen können, dass Spiele konsistent durchgeführt werden.
	Es kann nicht von ihnen verlangt werden, sich ständig an unterschiedliche Spieldurchführung **todo** bei unterschiedlichen Veranstaltungen oder in unterschiedlichen Ländern anzupassen.
	Zur Unterstützung der Konsistenz hat das Schiedsrichter- und Oberschiedsrichter-Komitee **todo** des ITTF[^fussnote:urc] eine Zusammenfassung empfohlener Handlungsweisen für Spielverantwortliche erstellt und als [][app:a], [][app:d], [][app:e] und [][app:f] beigelegt.

3. [][app:b] enthält die Anweisungen des ITTF für Spielverantwortliche bei Welt-Titelkämpfen **todo**, inclusive Weltmeisterschaften; diese Anweisungen sind nicht zwingend für andere Wettkämpfe, sie werden jedoch oft für kontinentale oder offene internationale Meisterschaften adaptiert.
	[][app:c] beschreibt die Qualifizierung von Schiedsrichtern und [][app:i] ist eine Zusammenfassung der Regel- und Regularienänderungen seit der letzten Ausgabe des Handbuchs 2007.


<!-- \appendix -->

# kommt noch [app:a]

# kommt noch [app:b]

# kommt noch [app:c]

# kommt noch [app:d]

# kommt noch [app:e]

# kommt noch [app:f]

# kommt noch [app:g]

# kommt noch [app:h]

# kommt noch [app:i]


[^fussnote:ittf]: `http://www.ittf.com`

[^fussnote:hbtr]: Handbook for Tournament Referees

[^fussnote:urc]: ITTF Umpires and Referees Committee (URC)

