Quotes Language:		germanguillemets
Base Header Level:	3
latex input:				basis-mmd-scrartcl
MyOptions:					font=droid, rules
latex input:				basis-mmd-style
Title:							Handbuch für Spielverantwortliche
MySubtitle:					OpenTT
Author:							Ekkart Kleinod
MyEmail:						schiri@ekkart.de
MyDate:							Stand: 14. Ausgabe, Juni 2011
latex input:				basis-mmd-begin-doc

<!--\newcommand{\todo}{\textcolor{purple}{~\textbf{todo}~}}-->

<!-- \maketitle -->

<!-- \section*{Vorwort} -->
<h3>Vorwort</h3>

Dies ist eine deutsche Übersetzung des "Handbook for Match Officials" der International Table Tennis Federation (ITTF).[^fussnote:ittf]
Die Übersetzung wird unabhängig von der ITTF angefertigt, die ITTF hat also mit der Korrektheit der Übersetzung nichts zu tun.

Wer einen Fehler oder eine bessere Übersetzung findet: einfach eine E-Mail schreiben oder per Git am Dokument mitschreiben.

Da mir die Übersetzung selbst schon viel Mühe bereitet, werde ich in der ersten Version auf durchgängiges Gendern verzichten, wer das übernehmen möchte ist herzlich dazu eingeladen.

Mit <!--\todo--> sind Stellen gekennzeichnet, deren Übersetzung mir noch nicht gut gefällt.

<!-- \cleardoublepage -->
<!-- \tableofcontents -->
<!-- \cleardoublepage -->


# Einleitung [sec:intro]

1. Der Zweck dieses Buchs ist es, Spielverantwortliche bei der Anwendung der Regeln und Regularien <!--\todo--> zu begleiten.
	Das Buch sollte in Verbindung mit dem aktuellen ITTF-Handbuch oder den Regeln gelesen werden.
	Dieses Buch beschäftigt sich hauptsächlich mit den Pflichten von Oberschiedsrichtern und deren Assistenten, enthält aber auch Aspekte der Aufgaben von Schiedsrichtern beim Leiten eines Spiels.
	Das "Handbuch für Oberschiedsrichter eines Turniers"[^fussnote:hbtr] beschreibt die weiteren Pflichten eines Oberschiedsrichters eines Turniers.

2. Spieler müssen sich darauf verlassen können, dass Spiele konsistent durchgeführt werden.
	Es kann nicht von ihnen verlangt werden, sich ständig an unterschiedliche Spieldurchführung <!--\todo--> bei unterschiedlichen Veranstaltungen oder in unterschiedlichen Ländern anzupassen.
	Zur Unterstützung der Konsistenz hat das Schiedsrichter- und Oberschiedsrichter-Komitee <!--\todo--> des ITTF[^fussnote:urc] eine Zusammenfassung empfohlener Handlungsweisen für Spielverantwortliche erstellt und als [][app:a], [][app:d], [][app:e] und [][app:f] beigelegt.

3. [][app:b] enthält die Anweisungen des ITTF für Spielverantwortliche bei Welt-Titelkämpfen <!--\todo-->, inklusive Weltmeisterschaften; diese Anweisungen sind nicht zwingend für andere Wettkämpfe, sie werden jedoch oft für kontinentale oder offene internationale Meisterschaften adaptiert.
	[][app:c] beschreibt die Qualifizierung von Schiedsrichtern und [][app:i] ist eine Zusammenfassung der Regel- und Regularienänderungen seit der letzten Ausgabe des Handbuchs 2007.


# Regeln und Regularien [sec:regeln]

1. Anwendbarkeit
	1. Die wichtigste Anforderung and Spielverantwortliche ist fundiertes Wissen der Regeln, **comprising laws** und Regularien, die Wettkampftischtennis bestimmen.
		Dazu kommt ein genaues Verständnis über das Ausmaß, in dem sie auf verschiedene Wettkampfformen angewendet werden.
		Die relevante Information darüber ist in den Kapiteln 2, 3 und 4 des ITTF-Handbuchs[^fussnote:hb] zu finden.

2. Regeln
	1. Die Tischtennisregeln, im Folgenden als "Regeln" bezeichnet, sind in Kapitel 2 des ITTF-Handbuchs enthalten.
		Die Regeln gelten für alle internationalen Spiele, sie werden üblicherweise von den Verbänden für ihre nationalen Wettkämpfe übernommen, wobei jeder Verband das Recht hat, Änderungen für Wettkämpfe einzuführen, die nur die Spieler des Verbands betreffen.
		Eine Regel kann nur bei einem General Meeting <!--\todo--> geändert werden, dazu sind 75% Zustimmung der Abstimmenden notwendig.

3. Regularien
	1. Kapitel 3 des ITTF-Handbuchs enthält die Regularien für internationale Wettkämpfe, die nachfolgend als "Regularien" bezeichnet werden.
		Die Regularien gelten grundsätzlich für alle internationalen Wettkämpfe.
		Die zusätzlichen Regularien für Welt-Titelkämpfe, inklusive Weltmeisterschaften, sind in Kapitel 4 verzeichnet.
		Diese Regularien können nur bei einem Treffen des ITTF Board of Directors <!--\todo--> durch einfache Mehrheit der Abstimmenden geändert werden.



<!-- \appendix -->

# kommt noch [app:a]

# kommt noch [app:b]

# kommt noch [app:c]

# kommt noch [app:d]

# kommt noch [app:e]

# kommt noch [app:f]

# kommt noch [app:g]

# kommt noch [app:h]

# kommt noch [app:i]


[^fussnote:ittf]: `http://www.ittf.com`

[^fussnote:hbtr]: Handbook for Tournament Referees

[^fussnote:urc]: ITTF Umpires and Referees Committee (URC)

[^fussnote:hb]: ITTF Handbook, deutsch: opentt-regeln, DTTB <!--\todo-->


